FROM nvidia/cuda:8.0-cudnn5-devel

MAINTAINER Jon Krohn <jon@untapt.com>

ENV PATH="/usr/local/cuda-8.0/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda-8.0/lib64:${LD_LIBRARY_PATH}"

## from core/Dockerfile-gpu
# Setup locales
RUN apt-get clean && apt-get update && apt-get install -y locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Purge existing python installs
RUN apt-get purge -y python.*

# Install prereqs
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential checkinstall \
	wget \
	bzip2 \
	ca-certificates \
	sudo \
	locales \
	fonts-liberation \
 && apt-get clean \ 
 && rm -rf /var/lib/apt/lists/*


## below mostly from jupyter/minimal-notebook (there's a bit of it in the line above too) 
## -- see https://github.com/jupyter/docker-stacks/blob/master/LICENSE.md
# Install Tini
RUN wget --quiet https://github.com/krallin/tini/releases/download/v0.10.0/tini && \
    echo "1361527f39190a7338a0b434bd8c88ff7233ce7b9a4876f3315c22fce7eca1b0 *tini" | sha256sum -c - && \
    mv tini /usr/local/bin/tini && \
    chmod +x /usr/local/bin/tini

# Configure environment
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH
ENV SHELL /bin/bash
ENV NB_USER jovyan
ENV NB_UID 1000
ENV HOME /home/$NB_USER

# Create jovyan user with UID=1000 and in the 'users' group 
RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER && \
	mkdir -p $CONDA_DIR && \
	chown $NB_USER $CONDA_DIR

USER $NB_USER

# Setup work directory for backward-compatibility
RUN mkdir /home/$NB_USER/work

# Install conda as jovyan and check the md5 sum provided on the download site
ENV MINICONDA_VERSION 4.3.21
RUN cd /tmp && \
    mkdir -p $CONDA_DIR && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh && \
    echo "c1c15d3baba15bf50293ae963abef853 *Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" | md5sum -c - && \
    /bin/bash Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh && \
    $CONDA_DIR/bin/conda config --system --prepend channels conda-forge && \
    $CONDA_DIR/bin/conda config --system --set auto_update_conda false && \
    $CONDA_DIR/bin/conda config --system --set show_channel_urls true && \
    $CONDA_DIR/bin/conda update --all && \
    conda clean -tipsy

# Install Jupyter Notebook and Hub
RUN conda install --quiet --yes \
    'notebook=5.0.*' \
    'jupyterhub=0.7.*' \
    'jupyterlab=0.24.*' \
    && conda clean -tipsy

USER root

EXPOSE 8888
WORKDIR $HOME

# Configure container startup
ENTRYPOINT ["tini", "--"]
CMD ["start-notebook.sh"]

# Add local files as late as possible to avoid cache busting
COPY docker-stack-scripts/start.sh /usr/local/bin/
COPY docker-stack-scripts/start-notebook.sh /usr/local/bin/
COPY docker-stack-scripts/start-singleuser.sh /usr/local/bin/
COPY docker-stack-scripts/jupyter_notebook_config.py /etc/jupyter/
RUN chown -R $NB_USER:users /etc/jupyter/

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_USER


## the next chunk of code is from jupyter/minimal-notebook 
## -- see https://github.com/jupyter/docker-stacks/blob/master/LICENSE.md


